server:
  port: 8777
spring:
  application:
    name: consul-micro-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
    consul:
      host: localhost
      port: 8500
      discovery:
        # 服务是否注册到consul,默认true
        #register: true
        #注册到consul的服务名称 consul-micro-service
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        #healthCheckInterval: 1s
        #instance-id是通过【application name】+ 【port】组成，如果只是用服务名称，同一个服务的多个实例注册会被覆盖；
        instanceId: ${spring.application.name}:${server.port}
        ip-address: ${spring.cloud.client.ipaddress}
        prefer-ip-address: true
        tags: local

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/marketing?characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 10
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 600000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#  redis:
#    host: 192.200.3.175
#    port: 6379
#    database: 0
#    #    password: root
#    # 连接池最大连接数(使用负值表示没有限制) 默认为8
#    lettuce.pool:
#      max-active: 8
#      # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
#      max-wait: -1ms
#      # 连接池中的最大空闲连接 默认为8
#      max-idle: 8
#      # 连接池中的最小空闲连接 默认为 0
#      min-idle: 0